// <auto-generated />
using System;
using LottoTicketGenerator.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(EntityFrameWorkContext))]
    [Migration("20231001215953_initiallottoticketdb")]
    partial class initiallottoticketdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("LottoTicketGenerator.Dom.LottoTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowSuperNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuperNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LottoTickets");
                });

            modelBuilder.Entity("LottoTicketGenerator.Dom.LottoTicketBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LottoTicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LottoTicketId");

                    b.ToTable("LottoTicketBoxes");
                });

            modelBuilder.Entity("LottoTicketGenerator.Dom.LottoTicketBox", b =>
                {
                    b.HasOne("LottoTicketGenerator.Dom.LottoTicket", "LottoTicket")
                        .WithMany("LottoTicketBoxes")
                        .HasForeignKey("LottoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("webapi.Dom.Generic.DistinctCollection<int>", "Numbers", b1 =>
                        {
                            b1.Property<int>("LottoTicketBoxId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Csv")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("LottoTicketBoxId");

                            b1.ToTable("LottoTicketBoxes");

                            b1.WithOwner()
                                .HasForeignKey("LottoTicketBoxId");
                        });

                    b.Navigation("LottoTicket");

                    b.Navigation("Numbers")
                        .IsRequired();
                });

            modelBuilder.Entity("LottoTicketGenerator.Dom.LottoTicket", b =>
                {
                    b.Navigation("LottoTicketBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
